Cwsf2MyosteoBundle_homepage:
    pattern:  /
    defaults: { _controller: Cwsf2MyosteoBundle:Default:index }

Cwsf2MyosteoBundle_admin:
    pattern:  /admin/
    defaults: { _controller: SonataAdminBundle:Core:dashboard }