cwsf2_myosteo_home:
    pattern:  /
    defaults: { _controller: Cwsf2MyosteoBundle:Default:index }

# La route initial du dashboard de l'administration est /admin/dashboard
# Pour simplifier on lie la route /admin/ avec le dashboard
cwsf2_myosteo_admin:
    pattern:  /admin/
    defaults: { _controller: SonataAdminBundle:Core:dashboard }