security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_SECRETARY:   ROLE_USER
        ROLE_THERAPIST:   ROLE_USER
        ROLE_ADMIN:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        user:
            pattern: ^/
            provider: fos_userbundle
            form_login:
                login_path: /user/login
                check_path: /user/login_check
            logout:
                path: /user/logout
                target: /
            anonymous: ~              

    access_control:
        - { path: ^/user/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/, roles: ROLE_ADMIN }        
